### ISSUE TITLE
Unable to drive 1301

### ISSUE THREAD

**Issue by Heltec-Aaron-Lee** [Lora-net/picoGW_mcu#2]
I downloaded this project and build it with Keil 5.23, but when I download the hex file created by this project or directly use hex files in bin folder, it seems some wrong here.

Computer can rean the com port, but the PicoGW Tools can't connect to device.

![2](https://user-images.githubusercontent.com/32860565/32877760-0183b84e-cade-11e7-99b5-1a34800d7018.jpg)
![default](https://user-images.githubusercontent.com/32860565/32877888-9882dffe-cade-11e7-9829-64a7ef5aa93b.png)

There are some warning when I build this project:
![default](https://user-images.githubusercontent.com/32860565/32877969-f5217d6a-cade-11e7-88ee-17be8befa0f6.png)
![default](https://user-images.githubusercontent.com/32860565/32877978-fe1c5ec6-cade-11e7-8669-7189e316127c.png)
![default](https://user-images.githubusercontent.com/32860565/32877983-05ac3148-cadf-11e7-9622-7b48b398a35d.png)

Does the problem caused by those warning? How can I fix them?

**Comment by goran-mahovlic** [comment]
Do you maybe have this tool it seams that it is not available for download.
I am trying to drive SX1301 to. 
I was able to get linux pkt_fwd to talk with SX1301, and it stops when it needs to get messages.
And when I try to read ID it is working every second time, not always, so there are still problems.
So I want to try this windows tool.
I do not know where to connect those pins on SX1301 concentrator board
FEM_EN
HSCLK_EN

**Comment by Heltec-Aaron-Lee** [comment]
Seems you system is not stable, check the power and XTL and RST singal, all of these are very important.

Mine 1301 works very stable in Liunx(both USB and SPI), but have problems with windows tools, can't read ID.

BTW. are you use the HEX file created by this project? can it working ?

**Comment by goran-mahovlic** [comment]
I have tried HEX file but it is not working with STM32F401 Nucleo board. 
It is not working because Nucleo does not have external oscilator.
So I did recompile the code and change it to use internal clock.
Ok, I will try to add external power (I have just use USB), check RST signal.
I did notice that GPIO0 led is not ON when module starts is this normal?
And on module both TX and RX are off.
And I did not know where on module to connect FEM_EN and HSCLK_EN.

**Comment by Heltec-Aaron-Lee** [comment]
You did a great job... may I have a try you recompile project with internal clock? My email is leehunter8801@outlook.com

![1](https://user-images.githubusercontent.com/32860565/33364601-162a1cce-d520-11e7-83c5-804ff3a16d0e.jpg)
You was using this Semtech's evaluate board? FEM_EN and HSCLK_EN had connected on the PCB. FEM_EN connected to STM32's PB0, I don't know HSCLK_EN too

Just USB power supply is enough, I means you should open it and check the power value make sure it right. 

I made a new board witch did't connect GPIO0 with any LEDs, TX and RX blinks when they are working.

**Comment by goran-mahovlic** [comment]
I am using RAK831 board, and cannot find HSCLK_EN and FEM_EN pins on that
board (probably they are named differently)
I will clone this repo and put my changes on git so we can get it to work...

**Comment by goran-mahovlic** [comment]
It is all up so you can try is it working for you 
https://github.com/goran-mahovlic/picoGW_mcu
check the changed pinout fiirst, and set is as you need
https://github.com/Lora-net/picoGW_mcu/compare/master...goran-mahovlic:master
If possible please let me know it it is working for you.
Tnx

**Comment by Heltec-Aaron-Lee** [comment]
OK... Thanks for you share. I will try it tomorrow.

**Comment by Heltec-Aaron-Lee** [comment]
I tested your codes, and changed the pins as my hardware, still not work.

There are some strang problem:
- Why STM32L4xx package is needed?
- Are you use UART for you board? I use the USB CDC port(I had comment the UART define part)

![default](https://user-images.githubusercontent.com/32860565/33383171-9309e516-d55d-11e7-8cf9-213e552d6d56.png)

![2](https://user-images.githubusercontent.com/32860565/33383856-67444258-d55f-11e7-93bb-cad8a5a13a0c.jpg)

**Comment by goran-mahovlic** [comment]
I am using UART. did not try to get it working with USB.
But will try to check how to use USB instead serial.
Do not know about L package I think it is not needed.
can you send me picoGW tools on my mail so I could try on windows with serial?
my mail is: goran.mahovlic@gmail.com

**Comment by GregCris** [comment]
Hello,

Sorry about his, we have a discrepancy between the code on GitHub and the PicoUI. To change this, you need to modifiy the file "usbd_desc.cpp" and change the USBD_DESC_Private_Defines (lines 59 to 66). Please, replace the #define with:

#define USBD_VID                      0x0483
#define USBD_PID_FS                   0x5740
#define USBD_LANGID_STRING            0x409
#define USBD_MANUFACTURER_STRING      "STMicroelectronics"
#define USBD_PRODUCT_STRING_FS        "SEMTECH PicoGW Virtual ComPort"
#define USBD_SERIALNUMBER_STRING_FS   "3EA5F0C2B81C"
#define USBD_CONFIGURATION_STRING_FS  "CDC Config"
#define USBD_INTERFACE_STRING_FS      "CDC Interface"

That should fix your issue.
