### ISSUE TITLE
NVIC_DisableIRQ;

### ISSUE THREAD

**Issue by x893** [Lora-net/picoGW_mcu#5]
Hi,
what real IRQ number used ?
picoGW_mcu\src\mbed-dev\targets\cmsis\TARGET_STM\TARGET_STM32F4\TARGET_NUCLEO_F401RE\system_stm32f4xx.c
Line 373: NVIC_DisableIRQ;
processing to __NVIC_DisableIRQ; and to
__STATIC_INLINE void __NVIC_DisableIRQ(IRQn_Type IRQn)
{
  NVIC->ICER[(((uint32_t)(int32_t)IRQn) >> 5UL)] = (uint32_t)(1UL << (((uint32_t)(int32_t)IRQn) & 0x1FUL));
}

Also Line 392: NVIC_EnableIRQ;

Thanks

**Comment by mcoracin** [comment]
Hi,

Hmmm, that's a good point, it actually does nothing!

We need to do some tests and see how this needs to be fixed.

Thank you!

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
