### ISSUE TITLE
CMDMANAGER CmdManager(PA_9, PA_10);

### ISSUE THREAD

**Issue by usernamevalis** [Lora-net/picoGW_mcu#7]
In the main file you initialize

`CMDMANAGER CmdManager(PA_9, PA_10);`
 
On the schematic PA_9 is connected to VCC, and and PA_10 is not connected to anything?
Is PA_9 is configured for OTG_VBUS_Sensing?

**Comment by mirzafahad** [comment]
That depends. If you are using UART (Enable Macro USE_UART), then that particular line will initialize the UART with those pins. If you are using USB then those two pins are not used by the CmdManager. Here is the code snippet:
```
#ifdef  USE_UART 
CMDMANAGER::CMDMANAGER(PinName Tx, PinName Rx)
{
    kill = false;
    ActiveInterface = (INTERFACE *) new COMUART (Tx, Rx);
    ActiveCom = ISUARTINTERFACE;
}
#else
CMDMANAGER::CMDMANAGER(PinName Tx, PinName Rx)
{
    kill = false;
    ActiveInterface = (INTERFACE *) new COMUSB ();
    ActiveCom = ISUSBINTERFACE;
}
#endif
```

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
